name: CD

on:
  push:
    branches:
      - 'release/v**'
    paths-ignore:
      - '**.md'

permissions:
  contents: write
  packages: write

jobs:
  docker-build:
    uses: ./.github/workflows/docker-build-and-push.yml
    with:
      dockerfile: ./Dockerfile
      push: true
  standalone-build:
    uses: ./.github/workflows/standalone-build.yml
  create-github-release:
    runs-on: ubuntu-latest
    needs: [docker-build, standalone-build]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    - uses: dotnet/nbgv@v0.4
      id: nbgv
    - uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: ZIP artifacts
      run: |
        7z a artifacts/fdd.zip ./artifacts/fdd/*
        7z a artifacts/win-x86.zip ./artifacts/win-x86/*
        7z a artifacts/win-x86-iis.zip ./artifacts/win-x86-iis/*
        7z a artifacts/linux-x64.zip ./artifacts/linux-x64/*
    - uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.nbgv.outputs.SemVer2 }}
        draft: true
        prerelease: false
        files: artifacts/*.zip
        target_commitish: ${{ github.sha }}
